name: Terraform Continuous Integration

on:
  workflow_dispatch:
    inputs:
      terraform_folder:
        description: 'Terraform configuration folder'
        required: true
        type: string
        default: 'none'

permissions:
  id-token: write
  contents: read

jobs:
  terraform-validate:
    name: Validate Terraform
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Path
        run: |
          if [ -d "./${{ github.event.inputs.terraform_folder }}" ]; then
            echo "Path /${{ github.event.inputs.terraform_folder }} exist"
          else
            echo "!!! Path /${{ github.event.inputs.terraform_folder }} does not exist !!!"
            echo "Please use one of the following subfolders as path:"
            ls -l
            exit 1
          fi

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: "1.9.6"

      - name: Terraform Init
        run: |
          terraform \
          -chdir="${{ github.event.inputs.terraform_folder }}" \
          init \
          -backend=false

      - name: Terraform Validate
        run: |
          terraform \
          -chdir="${{ github.event.inputs.terraform_folder }}" \
          validate

  terraform-plan:
    name: Terraform Plan
    needs: terraform-validate
    runs-on:
      self-hosted
    env:
      ARM_CLIENT_ID: "${{ vars.AZURE_CLIENT_ID_GH_LEARN }}"
      ARM_SUBSCRIPTION_ID: "${{ vars.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ vars.AZURE_TENANT_ID }}"
      ARM_USE_AZUREAD: true
      ARM_USE_OIDC: true
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: "1.9.6"

      - name: Terraform Init
        run: |
          terraform \
          -chdir="${{github.event.inputs.terraform_folder}}" \
          init \
          -backend-config="resource_group_name=${{vars.TFBACKEND_RESOURCE_GROUP}}" \
          -backend-config="storage_account_name=${{vars.TFBACKEND_STORAGE_ACCOUNT}}" \
          -backend-config="container_name=${{ github.event.inputs.terraform_folder }}" \
          -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        id: plan
        run: |
          terraform \
          -chdir="${{ github.event.inputs.terraform_folder }}" \
          plan \
          -input=false
