name: Test Pipeline on Public Runner

on:
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: self-hosted
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

  list-local-files:
    runs-on: self-hosted
    steps:
      - name: List Local Files
        run: ls -la
