name: Test Pipeline on Internal Runner

on:
  workflow_dispatch:

jobs:
  authenticate:
    name: 'Authenticate to Azure'
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Az CLI version
      run: |
        az version

    - name: Show account information
      run: |
        az account show

    - name: Get Key Vault secret
      id: get-secret
      run: |
        secret=$(az keyvault secret show --name atn-secret --vault-name kvatnmanual1 --query value -o tsv)
        echo "secret=$secret"
