name: Terraform State Management
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ID_001_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          #enable-AzPSSession: true

      - name: Checkout
        uses: actions/checkout@v4

      # - name: Bicep Installation
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: "2.30.0"
      #     inlineScript: |
      #       export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      #       az bicep install
      #       az bicep version
      
      - name: Install Bicep
        run: |
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
          az bicep install
          az bicep version
