name: Terraform State Management
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ID_001_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          #enable-AzPSSession: true

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Bicep
        run: |
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
          az bicep install
          az bicep version
      
      - name: Terraform State Storage Deployment
        run: |
          Date=$(date +'%Y-%m-%dT%H-%M-%S')
          TemplateFilePath='/actions-runner/_work/devops-infra/devops-infra/devops-infra/00-m-tfstatestore/bootstrap.bicep'
          Location="centralus"
          az deployment sub create --name "bootstrap-tfstorage-$Date" --location $Location --template-file $TemplateFilePath --what-if
